version: '3.8'

services:
  portal:
    build:
      context: ../../../..
      dockerfile: .devhub/deployment/development/docker/Dockerfile
    ports:
      - "4200:4200"
    environment:
      - NODE_ENV=development
    volumes:
      - ../../../../src:/app/src
      - ../../../../node_modules:/app/node_modules
    networks:
      - devhub-network

networks:
  devhub-network:
    driver: bridge
