apiVersion: v1
kind: Service
metadata:
  name: devhub-portal-prod-service
  namespace: devhub-prod
spec:
  selector:
    app: devhub-portal
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP
