apiVersion: v1
kind: Service
metadata:
  name: devhub-portal-cert-service
  namespace: devhub-cert
spec:
  selector:
    app: devhub-portal
    environment: certification
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP
